"""create_users_table

Revision ID: 486b0c94f474
Revises:
Create Date: 2026-04-03 11:46:26.298024

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "486b0c94f474"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.VARCHAR(length=36), type_=sa.Uuid(), existing_nullable=False
        )
        batch_op.alter_column(
            "email",
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=254),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=256),
            existing_nullable=False,
        )
        batch_op.drop_index(batch_op.f("ix_users_id"))
        batch_op.drop_column("updated_at")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("updated_at", sa.DATETIME(), nullable=False))
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.String(length=256),
            type_=sa.VARCHAR(length=255),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "email",
            existing_type=sa.String(length=254),
            type_=sa.VARCHAR(length=255),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id", existing_type=sa.Uuid(), type_=sa.VARCHAR(length=36), existing_nullable=False
        )

    # ### end Alembic commands ###
